### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character 

### ISSUE THREAD

**Issue by IgorPelevanyuk** [python-oca/python-oca#26]
```
import oca
client = oca.Client('login:pass', 'http://test.server.vom:2633/RPC2') 
oca.HostPool(client).info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/oca/pool.py", line 110, in info
    self._initialize_xml(data, self.pool_name)
  File "/usr/local/lib/python2.7/dist-packages/oca/pool.py", line 55, in _initialize_xml
    self.xml = ET.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0445' in position 31475: ordinal not in range(128)
```

**Comment by sysradium** [comment]
Hi there!

Try the code from PR #27 (or just the issue_26). If it fixes your problem I'll merge it into the master.

**Comment by IgorPelevanyuk** [comment]
Hello! 
Glad to the answer so fast!

About PR #27: I already tried to do the same. The following lines should be changed too in the same file.
Line 15:
```
def extractString(xml_or_string):
    if isinstance(xml_or_string, str) or isinstance(xml_or_string, unicode):
        return xml_or_string
    else:
        return xml_or_string.text or ''
```
But in the end I get nothing. I do not know why.

**Comment by sysradium** [comment]
Can you post the XML you get so I could debug it?
Also what encoding do you use on Nebula server?

**Comment by IgorPelevanyuk** [comment]
Well.  I think we can close this issue. I will answer in the following issue.
